drawer:
    caption:
    menu:
        ä¸»é¡µ:
            href: /
            icon: home
        å…³äº:
            href: /about
            icon: person
        å‹é“¾:
            href: /friend
            icon: link
        GitHub:
            href: https://github.com/TransparentLC
            icon: code
        å½’æ¡£:
            preset: archive
        RSS:
            preset: rss
            divider: true
        æ·±è‰²æ¨¡å¼:
            preset: dark
        è®¿é—®ç»Ÿè®¡:
            preset: stats_busuanzi

head:
    # favicon: /img/favicon.png
    # high_res_favicon: /img/favicon.png
    # apple_touch_icon: /img/favicon.png
    favicon: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/favicon.png
    high_res_favicon: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/favicon.png
    apple_touch_icon: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/favicon.png
    keywords:
    structured_data: true
    site_verification:
        google:
        baidu:

footer:
    since:
    text: Hosted by <a href="https://github.com/TransparentLC/transparentlc.github.io" target="_blank">Github Pages</a>

uiux:
    slogan: èº«å¤„å¯’å¤œ æŠŠæ¡æ˜Ÿå…‰âœ¨
    # sidebar_image: /img/sidebar_header.jpg
    sidebar_image: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/sidebar_header.jpg
    sidebar_image_color: '#958981'
    # banner_image: /img/daily_pic.png
    banner_image: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/daily_pic.png
    banner_image_color: '#f09ea3'
    # avatar: /img/avatar.jpg
    avatar: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/avatar.jpg
    mdui_primary_theme: pink
    mdui_accent_theme: pink
    post_thumbnail_color: '#f09ea3'
    copy_code_button_color: '#fff'
    top:
        enable: true
        # style: fab
        style: akarin

posts:
    default_excerpt: 120
    license: æœ¬ä½œå“é‡‡ç”¨<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯ã€‚ä¸å…è®¸å†…å®¹å†œåœºç±»ç½‘ç«™ã€CSDN ç”¨æˆ·å’Œå¾®ä¿¡å…¬ä¼—å·è½¬è½½ã€‚

links:
    default_avatar: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/Transparent_Akkarin.png
    # default_avatar: /img/Transparent_Akkarin.png
    description: >
        <div class="mdui-card mdui-hoverable mdui-m-y-2">
            <div class="mdui-card-content">
                <p>è™½ç„¶æ„Ÿè§‰æ˜¯â€œå¯èƒ½ä¸ä¼šæœ‰äººæ³¨æ„åˆ°çš„åœ°æ–¹â€ï¼Œä¸è¿‡å¦‚æœä½ æ³¨æ„åˆ°äº†è¿™é‡Œï¼Œé‚£å°±çœŸæ˜¯å¤ªå¥½äº†ï½</p>
                <p>é‚£ä¹ˆï¼Œè¦ä¸è¦åœ¨ä¸‹é¢çš„é“¾æ¥ä¸­å†å¯»æ‰¾ä¸€äº›ä½ å¯èƒ½ä¼šè§‰å¾—åŒæ ·æœ‰æ„æ€çš„ä¸œè¥¿å‘¢ï¼Ÿà©­ á•)à©­*â¾â¾</p>
                <p><a id="expand" href="javascript:;">æˆ‘æƒ³äº¤æ¢å‹é“¾ï¼</a></p>
                <div id="expand-content" class="mdui-hidden">
                    <p>ä¸€äº›å°è¦æ±‚ï¼š</p>
                    <ul>
                        <li>æ˜¯æ­å»ºåœ¨ GitHub Pages ä¸Šæˆ–è€…è‡ªå»ºçš„ä¸ªäººåšå®¢</li>
                        <li>æœ‰è‡³å°‘åç¯‡çš„åŸåˆ›ã€æœ‰æ„ä¹‰çš„å†…å®¹ï¼ˆ<kbd>Ctrl+C</kbd> å’Œ <kbd>Ctrl+V</kbd> ç¦æ­¢ï¼ï¼‰</li>
                        <li>æ”¯æŒ HTTPS ( à¥‘ê’³ à¥‘ )</li>
                        <li>ä¸è¦ğŸ•Šï¸ï¼Œæ¯”å¦‚è¿ç»­å¾ˆä¹…å¾ˆä¹…éƒ½æ²¡æœ‰æ›´æ–°ä»€ä¹ˆçš„(à¹‘Ë™ãƒ¼Ë™à¹‘)</li>
                        <li><strong>å·²ç»æŠŠè¿™ä¸ªå°ç«™æ·»åŠ åˆ°äº†è‡ªå·±çš„å‹é“¾åˆ—è¡¨ï½</strong></li>
                    </ul>
                    <blockquote>
                        <p>
                            ç«™ç‚¹åï¼šå­˜åœ¨æ„Ÿæ¶ˆå¤±çš„åœ°æ–¹|Ï‰â€¢`)
                            <br>
                            ä¸€å¥è¯ï¼šèº«å¤„å¯’å¤œ æŠŠæ¡æ˜Ÿå…‰âœ¨
                            <br>
                            åœ°å€ï¼š<a href="https://akarin.dev" target="_blank">https://akarin.dev</a>
                            <br>
                            å¤´åƒï¼š<a href="https://avatars0.githubusercontent.com/u/47057319" target="_blank">è¿™é‡Œè‡ªå–ï½ï¼ˆGitHub å¤´åƒï¼‰</a>
                        </p>
                    </blockquote>
                    <p>ç„¶åå°±å¯ä»¥åœ¨<a href="/about" target="_blank">å…³äº</a>é¡µé¢çš„è¯„è®ºåŒºé‡Œï¼ŒæŒ‰ç…§ä¸Šé¢çš„æ ¼å¼ç•™ä¸‹è‡ªå·±çš„ä¿¡æ¯å•¦ï¼æˆ‘çœ‹åˆ°äº†å°±ä¼šåŠ è¿›æ¥çš„( â€¢ Ì€Ï‰ âƒá·„)âœ§</p>
                    <p>ï¼ˆæœªæä¾›å¤´åƒçš„è¯ï¼Œé»˜è®¤æ˜¯<a href="https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/Transparent_Akkarin.png" target="_blank">è™šçº¿é˜¿å¡æ—</a>å“¦ï¼ï¼‰</p>
                    <small style="opacity:.2">ä¸è¿‡çœŸçš„ä¼šæœ‰èŠè‹£æ„¿æ„æ¥äº¤æ¢å‹é“¾å—(Â´â€¢ áµ• â€¢`)*</small>
                </div>
                <script>
                    document.getElementById('expand').onclick = () => document.getElementById('expand-content').classList.toggle('mdui-hidden');
                </script>
            </div>
        </div>
    list:
        "Will.K's Blog":
            link: https://williamkong.xyz
            avatar: https://ae01.alicdn.com/kf/HTB1no6ybaWs3KVjSZFxq6yWUXXaY.jpg
            description: ä¸€ä¸ªä¼¼ä¹ä¸å­˜åœ¨çš„åœ°æ–¹
        "Davinci çš„çº¢èŒ¶é¦†":
            link: https://davinciteahouse.com
            avatar: https://ae01.alicdn.com/kf/H4b5e98a3fcda4d01afcb691bc310495bb.jpg
            description: You are all stardust.
        "å·¦æ‰‹çš„ä¸–ç•Œ":
            link: https://risehere.net
            avatar:
            description: Rise's Blog
        "imByteCat":
            link: https://www.imbytecat.com
            avatar: https://ae01.alicdn.com/kf/H4bf8c8e611be46e786eb3b64204abf45U.jpg
            description: âœ¨ To reach the unreachable star.
        "å’¸é±¼ç™½çš„çª":
            link: https://blanca.world
            avatar: https://avatars.githubusercontent.com/u/29428546?s=160
            description: ä¸€äº›å¥‡å¥‡æ€ªæ€ªçš„ä¸œè¥¿
        "Misaka":
            link: https://railgun.icu
            avatar: https://avatars.githubusercontent.com/u/52127603?s=160
            description: Misaka Mikoto
        "Lost Space":
            link: https://hinwai.top
            avatar: https://hinwai.top/avatar.jpeg
            description: Hinux's Blog
        "Artist's Dream":
            link: https://rainartist.top
            avatar: https://avatars.githubusercontent.com/u/53852308?s=160
            description: It's better to burn out than to fade away
        "Bottle å°ç«™":
            link: https://bottle.moe
            avatar: https://avatars.githubusercontent.com/u/12976469?s=160
            description: SomeBottle's Blog
        "æ’ HengY1 æ¯…":
            link: https://hengy1.top
            avatar: https://avatars.githubusercontent.com/u/98681454?s=160
            description: æ²¡æœ‰æœ€å¼ºï¼Œåªæœ‰æ›´å¼º

comment:
    livere:
        # enable: false
        enable: true
        uid: MTAyMC80NDUwOC8yMTAzOQ==

stats:
    busuanzi:
        # enable: false
        enable: true
        script: https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/js/bsz.min.js
        site_uv: true
        site_pv: true
        page_pv: true

mathjax:

rss: /atom.xml

stylesheets:
# - /css/mdui.min.css
# - /css/prism-line-numbers.min.css
# - /css/prism-vsc-dark-plus.min.css
# - /css/APlayer.min.css
# - /css/style.css
- https://fastly.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/css/mdui.min.css
- https://fastly.jsdelivr.net/combine/npm/prismjs@1/plugins/line-numbers/prism-line-numbers.min.css,npm/prism-themes@1/themes/prism-vsc-dark-plus.min.css,npm/aplayer@1/dist/APlayer.min.css,gh/TransparentLC/transparentlc.github.io/css/style.min.css

scripts:
# - /js/APlayer.min.js
# - /js/mdui.min.js
# - /js/medium-zoom.min.js
# - /js/script.js
- https://fastly.jsdelivr.net/combine/gh/TransparentLC/transparentlc.github.io/js/mdui.min.js,npm/medium-zoom@1/dist/medium-zoom.min.js,npm/instant.page@5/instantpage.min.js,npm/aplayer@1/dist/APlayer.min.js,gh/TransparentLC/transparentlc.github.io/js/script.min.js
